// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF7MzJSjaMrxnoOb5ELe_6FZ156MwvEYM',
    appId: '1:365329128929:android:af94fae4934007097046a0',
    messagingSenderId: '365329128929',
    projectId: 'flappy-animal',
    storageBucket: 'flappy-animal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPpVEwDgigi9JC3E76jB7V_GbGgVe2PRs',
    appId: '1:365329128929:ios:fab8d80119c217a77046a0',
    messagingSenderId: '365329128929',
    projectId: 'flappy-animal',
    storageBucket: 'flappy-animal.appspot.com',
    iosBundleId: 'com.example.flappyanimal',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDMrtySeGPU-nySNdFtKyu4uPCipSuYYU',
    appId: '1:365329128929:web:a25e51f4a454ae7c7046a0',
    messagingSenderId: '365329128929',
    projectId: 'flappy-animal',
    authDomain: 'flappy-animal.firebaseapp.com',
    storageBucket: 'flappy-animal.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPpVEwDgigi9JC3E76jB7V_GbGgVe2PRs',
    appId: '1:365329128929:ios:fab8d80119c217a77046a0',
    messagingSenderId: '365329128929',
    projectId: 'flappy-animal',
    storageBucket: 'flappy-animal.appspot.com',
    iosBundleId: 'com.example.flappyanimal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDMrtySeGPU-nySNdFtKyu4uPCipSuYYU',
    appId: '1:365329128929:web:4c3ee6cb1b01c5497046a0',
    messagingSenderId: '365329128929',
    projectId: 'flappy-animal',
    authDomain: 'flappy-animal.firebaseapp.com',
    storageBucket: 'flappy-animal.appspot.com',
  );

}